<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>
    <PackageId>MIR.LsmasSharp</PackageId>
    <Version>0.1.0</Version>

    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
    <Title>LsmasSharp</Title>
    <Description>.NET video/audio provider based on L-SMASH-Works common logic and FFmpeg(lsmas), without bundling native binaries.</Description>
    <Authors>MIRIMIRIM</Authors>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/MIRIMIRIM/LsmasSharp.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/MIRIMIRIM/LsmasSharp</PackageProjectUrl>
    <PackageTags>lwlibavsource;l-smash-works;ffmpeg;video;audio</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
